###POST api/register
POST http://localhost:8080/api/register
Accept: application/json
Content-Type: application/json

{
  "username": "santoso",
  "password": "santoso123"
}

###POST api/login
POST http://localhost:8080/api/login
Accept: application/json
Content-Type: application/json

{
  "username": "santoso",
  "password": "santoso123"
}

###GET api/admin/user
GET http://localhost:8080/api/admin/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhbnRvc28iLCJleHAiOjE2OTM1MzI3Njd9.b8PCft9Op3Q4a_bmX8RFJZl0afkU968RAeIl4QL2-1U
Accept: application/json


